sqldb:
  qa_connection_string: 'DRIVER={ODBC Driver 17 for SQL Server};SERVER=dubnium\testsql16;DATABASE=qa_PanelRiderDB;UID=testdbuser;PWD=111111;'
  dev_connection_string: 'DRIVER={ODBC Driver 17 for SQL Server};SERVER=betelgeuse01,50201;DATABASE=PanelRiderDB;Trusted_Connection=yes;'
panels:
  em:
    id: 1029695
  ob:
    id: 161373312
  oy:
    id: 183597234
pr:
  login: admin@expertnoemnenie.ru
  passwd: 111111
  domain: https://cp.dev-pr.panelrider.com/
  qa_domain: http://qa.panelrider.com/
  dev_domain: https://cp.dev-pr.panelrider.com/
  api_path:
    1: api/v2/admin/panel/
  headers:
    accept: application/json
    content_type: application/json
test_data:
  existing_email: vsevolod.ovchinnikov@gmail.com
  user_id: 765264087
  project_id: 765179676
  culture: ru-Ru
  city_id: 11902
  country_id: 1019
  referrer_id: 900002
  referral_id: 768333820
  invitation_id: 765266400
  session_id: 765267453
  rating_user_id: 190868777
  json: {"Id": 765264087,"Name": "Тестр","Surname": "Тестр","BirthDate": "1999-06-21T00:00:00","Gender": 2,"PostalCode": null,"CountryId": 1001,"CountryName": "Российская Федерация","StateId": 2044,"StateName": "Калужская область","CityId": 10521,"CityName": null,"CurrencyId": 301,"CurrencyCode": null,"Rating": 100,"PassedSurveysCount": null,"LastPassedSurveyDT": null,"Age": 19}
  clientstaff_id: 1436505
  ct_proj_id: 765205094
  ct_proj_id_post: 765205094
  ct_proj_id_arch: 696433676
  ct_id: 765178869
  withdrawal_id: 748812048